### ISSUE TITLE
plotting script cannot handle missing values

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [bitly/data_hacks#34]
if uniq -c produces an empty count such as 
```
235054 
3629 0
136189 1
18418 10
 258 100
```
```
cat results/train_4.txt | bar_chart.py -a  --sort-keys
Traceback (most recent call last):
  File "/Users/aub3/portenv/bin/bar_chart.py", line 114, in <module>
    run(load_stream(sys.stdin), options)
  File "/Users/aub3/portenv/bin/bar_chart.py", line 52, in run
    data[kv[1]] += value
IndexError: list index out of range


```

**Comment by havanagrawal** [comment]
What would you expect this behavior to be, in case it has counted blanks? Ignore the blanks or show them in the bar chart?
